### ISSUE TITLE
Afbeeldingen inladen d.m.v. html

### ISSUE THREAD

**Issue by Stefan-Espant** [KaanKalmi/Squad-page#1]
Gebruik html voor het inladen van afbeeldingen in plaats van css.
Hier is een link hoe je dat goed kan toepassen:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

https://github.com/KaanKalmi/Squad-page/blob/c39742ee3b13dc9482d9be1396433a08508831fd/styles/style.css#L11-L16

**Comment by KaanKalmi** [comment]
gefixt.
